# Generated by Django 5.0.6 on 2024-11-03 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_resultadoevaluacion_fecha'),
        ('usuarios', '0018_remove_usuario_slug_usuario_enlace_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textura', models.CharField(max_length=50)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('materia_organica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacidad_intercambio_cat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drenaje', models.CharField(max_length=50)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('erosion', models.CharField(max_length=50)),
                ('compactacion', models.CharField(max_length=50)),
                ('calidad_suelo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recomendaciones', models.TextField()),
                ('posibles_riesgos', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
