# Generated by Django 5.0.6 on 2024-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_resultadosuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosuelo',
            name='altitud',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='azufre',
            field=models.DecimalField(decimal_places=2, default=6.4, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='boro',
            field=models.DecimalField(decimal_places=2, default=5.6, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='calcio',
            field=models.DecimalField(decimal_places=2, default=6.3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='cantidades_aplicadas',
            field=models.TextField(default=7.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='cobre',
            field=models.DecimalField(decimal_places=2, default=5.7, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='fertilizantes',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='fosforo',
            field=models.DecimalField(decimal_places=2, default=6.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='frecuencia_aplicacion',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='hierro',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='magnesio',
            field=models.DecimalField(decimal_places=2, default=4.3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='manganeso',
            field=models.DecimalField(decimal_places=2, default=6.8, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='molibdeno',
            field=models.DecimalField(decimal_places=2, default=4.2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='nitrogeno',
            field=models.DecimalField(decimal_places=2, default=5.3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='potasio',
            field=models.DecimalField(decimal_places=2, default=6.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='salinidad',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='zinc',
            field=models.DecimalField(decimal_places=2, default=4.6, max_digits=5),
            preserve_default=False,
        ),
    ]
