# Generated by Django 5.0.6 on 2024-11-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_remove_resultadosuelo_capacidad_intercambio_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadosuelo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Resultado de Suelo', 'verbose_name_plural': 'Resultados de Suelo'},
        ),
    ]
