# Generated by Django 5.0.6 on 2024-11-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_alter_resultadosuelo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosuelo',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='humedad',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadosuelo',
            name='temperatura',
            field=models.FloatField(default=28),
            preserve_default=False,
        ),
    ]
