# Generated by Django 5.0.6 on 2024-07-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_usuario_id_alter_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('tipo_calle', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero1', models.CharField(max_length=10)),
                ('numero2', models.IntegerField()),
                ('area', models.IntegerField()),
                ('nivelacion', models.CharField(choices=[('Plano', 'Plano'), ('Pendiente', 'Pendiente')], max_length=50)),
                ('tipo_suelo', models.CharField(choices=[('Arcilloso', 'Arcilloso'), ('Arenoso', 'Arenoso'), ('Limoso', 'Limoso')], max_length=50)),
                ('caficultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.caficultor')),
            ],
        ),
    ]
