# Generated by Django 5.0.6 on 2024-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='tipo_suelo',
            field=models.CharField(choices=[('Arcilloso', 'Arcilloso'), ('Arenoso', 'Arenoso'), ('Franco', 'Franco')], max_length=50),
        ),
    ]
