# Generated by Django 5.0.6 on 2024-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.BigIntegerField()),
                ('tipo_usuario', models.CharField(choices=[('Caficultor', 'Caficultor'), ('UserAsociacion', 'Usuario de Asociación'), ('AdminAsociacion', 'Administrador de Asociación'), ('Insumos', 'Proveedor de Insumos')], max_length=20)),
                ('contrasena', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
            ],
        ),
    ]
