# Generated by Django 5.0.6 on 2024-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Caficultor', 'Caficultor'), ('UserAsociacion', 'Usuario de Asociación'), ('AdminAsociacion', 'Administrador de Asociación'), ('Insumos', 'Proveedor de Insumos')], max_length=35),
        ),
    ]
