# Generated by Django 5.0.6 on 2024-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_administradorasociacion_caficultor_proveedorinsumos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=250),
        ),
    ]
