# Generated by Django 5.0.6 on 2024-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_administradorcoffeeweb_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='../static/img/profile.jpg', null=True, upload_to='../media/profile_pics/'),
        ),
    ]
