# Generated by Django 5.0.6 on 2024-07-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='identificacion',
        ),
    ]
