# Generated by Django 5.0.6 on 2024-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_descripcion_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidos',
            field=models.ManyToManyField(related_name='seguidores', to='usuarios.usuario'),
        ),
    ]
