# Generated by Django 5.0.6 on 2024-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_usuario_seguidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(default=202407011, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
