# Generated by Django 5.0.6 on 2024-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_usuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
