# Generated by Django 5.0.6 on 2024-07-05 18:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_usuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id', unique=True),
        ),
    ]
