# Generated by Django 5.0.6 on 2024-07-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_usuario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='slug',
        ),
        migrations.AddField(
            model_name='usuario',
            name='enlace_perfil',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
